eureka:
  instance:
    non-secure-port: 80
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: ${EUREKA_URI:https://user:${REGISTRY_SERVER_PASSWORD:password}@icu-registry.herokuapp.com/eureka}

management:
  security:
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

spring:
  rabbitmq:
    host: woodpecker.rmq.cloudamqp.com
    port: 5672
    username: kdmffedc
    password: ENC(CsUZ58Eb0zuABi41WRxVEXYgaqYIwxFMLJMYQRXzBQAL/Koi08Njxv80yHZgJdqR)
    virtual-host: kdmffedc
  sleuth:
    sampler:
      percentage: 1
    integration:
      enabled: false
    scheduled:
      skip-pattern: "^org.*HystrixStreamTask$"

  datasource:
    url: jdbc:mysql://sql11.freemysqlhosting.net/sql11507946?createDatabaseIfNotExist=true
    username: sql11507946
    password: ENC(gILFyJzsLi6aUnMwcbSt6jHGecuT91L8)
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update

jasypt:
  encryptor:
    password: jazaradebuggers