eureka:
  instance:
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info
    non-secure-port: 80
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: ${EUREKA_URI:https://user:${REGISTRY_SERVER_PASSWORD:password}@icu-registry.herokuapp.com/eureka}

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

spring:
  rabbitmq:
    host: woodpecker.rmq.cloudamqp.com
    port: 5672
    username: kdmffedc
    password: ENC(CsUZ58Eb0zuABi41WRxVEXYgaqYIwxFMLJMYQRXzBQAL/Koi08Njxv80yHZgJdqR)
    virtual-host: kdmffedc
  sleuth:
    sampler:
      percentage: 1
    integration:
      enabled: false
    scheduled:
      skip-pattern: "^org.*HystrixStreamTask$"

  datasource:
    url: jdbc:mysql://sql8.freemysqlhosting.net/sql8507958?createDatabaseIfNotExist=true
    username: sql8507958
    password: ENC(IijcfwN/lwh/HsKlpYNPxVtPUASm6Z83)
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL55Dialect
    show-sql: true
    hibernate:
      ddl-auto: create

jasypt:
  encryptor:
    password: jazaradebuggers