server:
  port: ${PORT:5000}

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 200000

ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 30000

zuul:
  ignoredServices: '*'
  routes:
    registration-service:
      serviceId: registration-service
      path: /registration/**

eureka:
  instance:
    hostname: auth-icu.herokuapp.com

secret: jazaradebuggers

# Enable multipart uploads
spring:
  servlet:
    multipart:
      enabled: true
    # Threshold after which files are written to disk.
    file-size-threshold: 2KB
    # Max file size.
    max-file-size: 10MB
    # Max Request Size
    max-request-size: 20MB
    ## File Storage Properties
    # All files uploaded through the REST API will be stored in this directory
    file.upload-dir: /app