server:
  port: ${PORT:5000}

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 200000

ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 30000

zuul:
  ignoredServices: '*'
  routes:
    registration-service:
      serviceId: registration-service
      path: /registration/**

eureka:
  instance:
    hostname: auth-icu.herokuapp.com

secret: jazaradebuggers

# Enable multipart uploads
spring:
  servlet:
    multipart:
      enabled: true
    # Threshold after which files are written to disk.
    file-size-threshold: 2KB
    # Max file size.
    max-file-size: 10MB
    # Max Request Size
    max-request-size: 20MB
    ## File Storage Properties
    # All files uploaded through the REST API will be stored in this directory
    file.upload-dir: /app

  datasource:
    url: jdbc:postgresql://ec2-44-206-214-233.compute-1.amazonaws.com:5432/dcsac689pnlu7m?createDatabaseIfNotExist=true
    username: hjbmhcprojlhek
    password: ENC(NLQtuZRwS3tzNjJNWGiP2Hqm+VjC0Zj9e0I9R2HDAbQgvxKHYwD6n94Gb2XfQhTDKARlx0rtCzb3ZVUhPUUd8yioqDE8xTKgaxrkXB6DvoM=)
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update