server:
  port: ${PORT:5000}

management:
  security:
    enabled: false
  context-path: /mgmt

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 30000

zuul:
  ignoredServices: '*'
  routes:
    registration-service:
      path: /registration/**
      sensitiveHeaders:
    serviceId: registration-service

eureka:
  instance:
    hostname: auth-icu.herokuapp.com
    health-check-url-path: auth-icu.herokuapp.com/mgmt/health
    status-page-url-path: auth-icu.herokuapp.com/mgmt/info
    metadata-map:
      management.context-path: auth-icu.herokuapp.com/mgmt

secret: jazaradebuggers