server:
  port: ${PORT:5000}

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 200000

ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 30000

zuul:
  ignoredServices: '*'
  routes:
    registration-service:
      serviceId: registration-service
      path: /registration/**
      stripPrefix: false

eureka:
  instance:
    hostname: auth-icu.herokuapp.com

secret: jazaradebuggers