server:
  port: ${PORT:8080}

name: consumecam

eureka:
  instance:
    hostname: consumecam-icu.herokuapp.com
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}