server:
  port: ${PORT:8081}

name: consumecam

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}