server:
  port: ${PORT:8081}

name: consumecam

eureka:
  instance:
    hostname: icu-consumecam.herokuapp.com
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}