server:
  port: ${PORT:8080}

name: registration

eureka:
  instance:
    hostname: registration-icu.herokuapp.com

spring:
  mail:
    host: smtp.gmail.com
    port: 465
    protocol: smtps
    username: yassarhammami@gmail.com
    password: ENC(jS0l335mHoWpZk3KyypXKOaf2dRSz/5j+2K7ARd5HeA=)
    properties:
      mail:
        transport:
          protocol: smtps
        smtps:
          auth: true
          starttls:
            enable: true
          timeout: 20000

support:
  email: yassarhammami@gmail.com
