server:
  port: ${PORT:8080}

name: registration

eureka:
  instance:
    hostname: registration-icu.herokuapp.com

spring:
  mail:
    host: smtp.gmail.com
    port: 465
    protocol: smtps
    username: yassarhammami@gmail.com
    password: ENC(jS0l335mHoWpZk3KyypXKOaf2dRSz/5j+2K7ARd5HeA=)
    properties:
      mail:
        transport:
          protocol: smtps
        smtps:
          auth: true
          starttls:
            enable: true
          timeout: 20000


  datasource:
    url: jdbc:mysql://sql8.freemysqlhosting.net/sql8507958?createDatabaseIfNotExist=true
    username: sql8507958
    password: ENC(IijcfwN/lwh/HsKlpYNPxVtPUASm6Z83)
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL55Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

support:
  email: yassarhammami@gmail.com

