server:
  port: ${PORT:8080}

name: registration

eureka:
  instance:
    hostname: registration-icu.herokuapp.com
    non-secure-port: 80
    prefer-ip-address: false

spring:
  mail:
    host: smtp.gmail.com
    port: 465
    protocol: smtps
    username: yassarhammami@gmail.com
    password: mfalrrenjnufcvvo
    properties:
      mail:
        transport:
          protocol: smtps
        smtps:
          auth: true
          starttls:
            enable: true
          timeout: 20000

support:
  email: yassarhammami@gmail.com
