spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:config/
  rabbitmq:
    host: woodpecker.rmq.cloudamqp.com
    port: 5672
    username: kdmffedc
    password: ENC(CsUZ58Eb0zuABi41WRxVEXYgaqYIwxFMLJMYQRXzBQAL/Koi08Njxv80yHZgJdqR)
    virtual-host: kdmffedc

management:
  security:
    enabled: false

server:
  port: ${PORT:8888}

eureka:
  instance:
    hostname: config-icu.herokuapp.com
    non-secure-port: 80
    prefer-ip-address: false
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: https://user:${REGISTRY_SERVER_PASSWORD:password}@registry-icu.herokuapp.com/eureka/

jasypt:
  encryptor:
    password: jazaradebuggers