spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:config/
  rabbitmq:
    host: woodpecker.rmq.cloudamqp.com
    port: 5672
    username: kdmffedc
    password: 2-W4eKdkrc0nUY4x12OjUFQC5_akBHwG
    virtual-host: kdmffedc

management:
  security:
    enabled: false

server:
  port: ${PORT:8888}

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: https://user:${REGISTRY_SERVER_PASSWORD:password}@registry-icu.herokuapp.com/eureka/

security:
  user:
    name: user
    password: ${CONFIG_SERVER_PASSWORD:password}
