spring:
  boot:
    admin:
      client:
        url: https://icu-monitor.herokuapp.com
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:config/
  rabbitmq:
    host: woodpecker.rmq.cloudamqp.com
    port: 5672
    username: kdmffedc
    password: ENC(CsUZ58Eb0zuABi41WRxVEXYgaqYIwxFMLJMYQRXzBQAL/Koi08Njxv80yHZgJdqR)
    virtual-host: kdmffedc
  security:
    user:
      name: user
      password: ${CONFIG_SERVER_PASSWORD:password}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false

server:
  port: ${PORT:8888}

eureka:
  instance:
    hostname: icu-config.herokuapp.com
    non-secure-port: 80
    prefer-ip-address: false
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    service-url:
      defaultZone: ${EUREKA_URI:https://user:${REGISTRY_SERVER_PASSWORD:password}@icu-registry.herokuapp.com/eureka}


jasypt:
  encryptor:
    password: jazaradebuggers